/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/lib')['App']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ASpace: typeof import('ant-design-vue/lib')['Space']
    ATag: typeof import('ant-design-vue/lib')['Tag']
    StarTwoTone: typeof import('@ant-design/icons-vue')['StarTwoTone']
  }
}
